# Generated by Django 6.0.2 on 2026-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('request_created', 'Request Created'), ('offer_received', 'Offer Received'), ('offer_accepted', 'Offer Accepted'), ('offer_rejected', 'Offer Rejected'), ('task_assigned', 'Task Assigned'), ('task_status_updated', 'Task Status Updated'), ('request_matched', 'Request Matched'), ('request_completed', 'Request Completed'), ('verification_updated', 'Verification Updated'), ('donation_made', 'Donation Made'), ('campaign_created', 'Campaign Created'), ('campaign_approved', 'Campaign Approved'), ('campaign_goal_reached', 'Campaign Goal Reached'), ('system', 'System')], max_length=40),
        ),
    ]
