# Generated by Django 5.1.7 on 2026-03-23 14:40

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(db_index=True, max_length=6, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.users.models._default_expires_at_10min)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_passwordresetotp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
