# Generated by Django 5.1.7 on 2026-03-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_organ_pledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_blood_donation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organ_pledge_details',
            field=models.TextField(blank=True, default=''),
        ),
    ]
