# Generated by Django 5.1.7 on 2026-03-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('esewa', 'eSewa'), ('mock', 'Mock')], default='stripe', max_length=20),
        ),
    ]
