# Generated by Django 6.0.1 on 2026-02-02 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('task_status', models.CharField(choices=[('assigned', 'Assigned'), ('picked', 'Picked'), ('delivered', 'Delivered')], default='assigned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volunteer_tasks', to='donations.donationoffer')),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_tasks', to='donations.donationrequest')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_volunteer_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
