# Generated by Django 5.1.7 on 2026-03-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0010_donation_blood_volunteer_coords'),
        ('volunteers', '0003_volunteer_nullable_pending_decline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_tasks', to='donations.donation'),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteertask',
            name='donation_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_tasks', to='donations.donationrequest'),
        ),
        migrations.AddConstraint(
            model_name='volunteertask',
            constraint=models.CheckConstraint(condition=models.Q(('donation_request__isnull', False), ('donation__isnull', False), _connector='OR'), name='volunteer_task_request_or_standalone_donation'),
        ),
    ]
