# Generated by Django 5.1.7 on 2026-04-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_default_rewards(apps, schema_editor):
    Reward = apps.get_model('volunteers', 'Reward')
    defaults = [
        ('Certificate', 50),
        ('Badge', 100),
        ('Voucher', 150),
    ]
    for name, required_points in defaults:
        Reward.objects.get_or_create(
            name=name,
            defaults={
                'required_points': required_points,
                'is_active': True,
            },
        )


def unseed_default_rewards(apps, schema_editor):
    Reward = apps.get_model('volunteers', 'Reward')
    Reward.objects.filter(name__in=['Certificate', 'Badge', 'Voucher']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_donation_blood_volunteer_coords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteertask',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteertask',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('required_points', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'volunteers_reward',
                'ordering': ['required_points', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField()),
                ('date_redeemed', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='volunteers.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'volunteers_redemption',
                'ordering': ['-date_redeemed'],
                'constraints': [models.UniqueConstraint(fields=('user', 'reward'), name='volunteers_unique_reward_per_user')],
            },
        ),
        migrations.RunPython(seed_default_rewards, unseed_default_rewards),
    ]
