# Generated by Django 6.0.1 on 2026-02-02 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationoffer',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationoffer',
            name='donation_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='donations.donationrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='donationoffer',
            unique_together={('donor', 'donation_request')},
        ),
    ]
