# Generated by Django 5.1.7 on 2026-03-22 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_donationoffer_fulfillment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('funds', 'Funds'), ('blood', 'Blood'), ('organ', 'Organ'), ('other', 'Other')], max_length=20)),
                ('donation_type', models.CharField(choices=[('material', 'Material'), ('money', 'Money')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('fulfillment_type', models.CharField(choices=[('self_dropoff', 'I will drop off myself'), ('volunteer_pickup', 'Request a volunteer pickup')], default='self_dropoff', max_length=20)),
                ('pickup_location', models.CharField(blank=True, max_length=512)),
                ('pickup_latitude', models.FloatField(blank=True, null=True)),
                ('pickup_longitude', models.FloatField(blank=True, null=True)),
                ('delivery_location', models.CharField(blank=True, help_text='Drop-off / recipient address for volunteer delivery (standalone).', max_length=512)),
                ('delivery_latitude', models.FloatField(blank=True, null=True)),
                ('delivery_longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation_request', models.ForeignKey(blank=True, help_text='Null = general donation not tied to a specific NGO request.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.donationrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations_donation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodDonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(blank=True, help_text='e.g. standalone, offer_delivered, payment, volunteer_delivered', max_length=48)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donation_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations_blood_donation_record',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['user', '-recorded_at'], name='donations_b_user_id_e1820a_idx')],
            },
        ),
    ]
