# Generated by Django 5.1.7 on 2026-03-28 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_donationmatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donationrequest',
            name='remaining_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Auto-calculated remaining quantity', null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('partially_fulfilled', 'Partially Fulfilled'), ('fulfilled', 'Fulfilled'), ('completed', 'Completed'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.CreateModel(
            name='UserItemDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='donations/images/')),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('CREATED', 'Created - Available'), ('REQUESTED', 'Requested by Receiver'), ('ACCEPTED', 'Accepted by Donor'), ('SCHEDULED', 'Pickup Scheduled'), ('ON_THE_WAY', 'On the Way (Out for Delivery)'), ('COMPLETED', 'Completed (Received)')], default='CREATED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p2p_donations_given', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p2p_donations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations_useritemdonation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created - Available'), ('REQUESTED', 'Requested by Receiver'), ('ACCEPTED', 'Accepted by Donor'), ('SCHEDULED', 'Pickup Scheduled'), ('ON_THE_WAY', 'On the Way (Out for Delivery)'), ('COMPLETED', 'Completed (Received)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='donations.useritemdonation')),
            ],
            options={
                'db_table': 'donations_donationstatushistory',
                'ordering': ['-timestamp'],
            },
        ),
    ]
