# Generated by Django 5.1.7 on 2026-04-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0012_donationrequest_remaining_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('books', 'Books'), ('funds', 'Funds'), ('blood', 'Blood'), ('organ', 'Organ'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('clothes', 'Clothes'), ('books', 'Books'), ('funds', 'Funds'), ('blood', 'Blood'), ('organ', 'Organ'), ('other', 'Other')], max_length=20),
        ),
    ]
