# Generated by Django 5.1.7 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_donation_assigned_volunteer_donation_points_awarded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Required for food donations. Item expiry datetime.', null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Last datetime this donation should be considered valid for matching/listing.', null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
